name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # build monthly for automatic patches
  schedule:
    - cron:  '37 15 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Checkout Speedtest
        run: git clone https://github.com/lukealford/abb-speedtest-cli.git
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build speedtest
        id: docker_build_speedtest
        uses: docker/build-push-action@v6
        with:
          context: abb-speedtest-cli
          push: false
          load: true
          tags: abb-speedtest
      -
        name: docker images
        run: docker images
      -
        name: Build and push Aussiebbmgt
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gergnz/aussiebbmgt:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
